---
name: 'actionshub-chef-install'
author: 'Jason Field'
description: 'Installs Chef on your linux build agent with ease'
inputs:
  channel:
    description: 'Chef Channel to install, stable or current'
    required: false
    default: 'stable'
  project:
    description: 'which chef project to install, chef-workstation or chefdk'
    required: false
    default: 'chef-workstation'
  version:
    description: 'version to install, default is latest'
    required: false
  chefDownloadUrl:
    description: 'Chef download base url, defaults to https://docs.chef.io/download/community/'
    required: false
    default: 'chefdownload-community.chef.io'
  license:
    description: 'license key, required if using https://docs.chef.io/download/commercial/'
    required: false
  windowsPath:
    description: 'Path to the root of the chef install. Windows Only'
    required: false
    default: 'C:\opscode\chef-workstation\'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'download'
  color: 'red'
