---
name: 'actionshub-chef-install'
author: 'Jason Field'
description: 'Installs Chef on your linux build agent with ease'
inputs:
  channel:
    description: 'Chef Channel to install, stable or current'
    required: false
    default: 'stable'
  project:
    description: 'which chef project to install, chef-workstation or chefdk'
    required: false
    default: 'chef-workstation'
  version:
    description: 'version to install, default is latest'
    required: false
  omnitruckUrl:
    description: 'Omnitruck base url'
    required: false
    default: 'omnitruck.chef.io'
  windowsPath:
    description: 'Path to the root of the chef install. Windows Only'
    required: false
    default: 'C:\opscode\chef-workstation\'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'download'
  color: 'red'
