---
name: 'actionshub-chef-install'
author: 'Jason Field'
description: 'Installs Chef on your linux build agent with ease'
inputs:
  channel:
    description: 'Chef Channel to install, stable or current'
    required: false
    default: 'stable'
  project:
    description: 'which chef project to install, chef-workstation or chefdk'
    required: false
    default: 'chef-workstation'
  version:
    description: 'Version to install. Defaults to 21.6.497 for chef-workstation (last version with test-kitchen 2.x). Set to "latest" to get the newest version.'
    required: false
  omnitruckUrl:
    description: 'Omnitruck base url'
    required: false
    default: 'omnitruck.chef.io'
  windowsPath:
    description: 'Path to the root of the chef install. Windows Only'
    required: false
    default: 'C:\opscode\chef-workstation\'
runs:
  using: composite
  steps:
    - name: Install Chef (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
        PROJECT: ${{ inputs.project }}
        VERSION: ${{ inputs.version }}
        OMNITRUCK_URL: ${{ inputs.omnitruckUrl }}
      run: |
        set -o pipefail
        if [ -z "$VERSION" ] && [ "$PROJECT" = "chef-workstation" ]; then
          VERSION="21.6.497"
        fi
        VERSION_FLAG=""
        [ -n "$VERSION" ] && VERSION_FLAG="-v ${VERSION}"
        curl -fsSL "https://${OMNITRUCK_URL}/install.sh" \
          | sudo bash -s -- -c "${CHANNEL}" -P "${PROJECT}" ${VERSION_FLAG}

    - name: Install Chef (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        CHANNEL: ${{ inputs.channel }}
        PROJECT: ${{ inputs.project }}
        VERSION: ${{ inputs.version }}
        OMNITRUCK_URL: ${{ inputs.omnitruckUrl }}
      run: |
        if (-not $env:VERSION -and $env:PROJECT -eq "chef-workstation") {
          $env:VERSION = "21.6.497"
        }
        $vFlag = if ($env:VERSION) { "-version $env:VERSION" } else { "" }
        . { iwr -useb "https://$env:OMNITRUCK_URL/install.ps1" } | iex
        install -channel $env:CHANNEL -project $env:PROJECT $vFlag

    - name: Add Chef to PATH (Windows)
      if: runner.os == 'Windows'
      shell: bash
      env:
        WINDOWS_PATH: ${{ inputs.windowsPath }}
      run: echo "${WINDOWS_PATH}bin" >> "$GITHUB_PATH"
branding:
  icon: 'download'
  color: 'red'
